version: '3.8'

services:
  app:
    image: losokos/ai-support-bot:latest
    container_name: ai-support-bot-app
    ports:
      - "${APP_PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - NODE_OPTIONS=${NODE_OPTIONS:---experimental-vm-modules --no-warnings}
      # Application specific ENV variables
      - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
      - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_SECRET=${DISCORD_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

# Usunięto wszystkie definicje usług Supabase (kong, db, auth, rest, itd.)
# oraz 'volumes: supabase_db_data' i 'networks: supabase_network'
# Supabase CLI będzie zarządzać tymi komponentami i ich danymi.

# Usunięto opcjonalne healthcheck dla Twojej aplikacji
# healthcheck:
#   test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-3000}/api/health || exit 1"]
#   interval: 30s
#   timeout: 10s
#   retries: 3
#   start_period: 60s 